name: clearwater_riverine
channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.10
  - scipy # installs numpy, pandas and most pyData libraries
  - geopandas
  - spatialpandas
  - xarray
  - cf_xarray  # Interprets CF Convention attributes for Xarray objects
  - h5py
  - hdf5plugin  # HDF5 compression filters for h5py
  - gridgeo  # Convert UGRID and SGRID compliant files to a variety of geo-like objects. https://github.com/pyoceans/gridgeo
  - netCDF4
  - zarr
  - numcodecs # buffer compression and transformation codecs for use by zarr
  - bottleneck # speeds up NaN-skipping and rolling window aggregations by a large factor
  - fastparquet

  # HoloViz, https://holoviz.org
  - hvplot  # hvPlot installs most HoloViz libs
  - geoviews

  # Interactivity via Jupyter Notebooks
  - jupyterlab
  - nodejs  # required for many extensions
  - ipympl  # jupyter-matplotlib, https://github.com/matplotlib/ipympl
  - ipywidgets  # Required for HoloViz interactivity

# Dev tools: Language Server Protocol (LSP) (Optional), for:
  # code navigation + hover suggestions + linters + autocompletion + rename
  - python-lsp-server # LSP extension for Python (pylsp), including:
    # Rope for Completions and renaming
    # Pyflakes linter to detect various errors
    # McCabe linter for complexity checking
    # pycodestyle linter for style checking
    # pydocstyle linter for docstring style checking (disabled by default)
    # autopep8 for code formatting
    # YAPF for code formatting (preferred over autopep8)
    # flake8 for error checking (disabled by default)
    # pylint for code linting (disabled by default)
  - pylsp-mypy # MyPy type checking for Python >=3.7.
  - jupyterlab-lsp # Provides both server extension and lab extension

  # package management
  - conda
  - conda-build
  - conda-libmamba-solver  # Faster env solver, https://conda.github.io/conda-libmamba-solver/
