[workspace]
name = "clearwater_riverine"
version = "0.6.0"
description = "Clearwater Riverine modeling package"
authors = ["Sarah Jordan"] # Pixi requires an authors field
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
# This is where you define your Python version requirement in Pixi
python = ">=3.11"
scipy = "*"
numba = "*"
dask = "*"
xarray = "*"
cf-xarray = "*"
h5py = "*"
hdf5plugin = "*"
gridgeo = "*"
netCDF4 = "*"
zarr = "*"
numcodecs = "*"
bottleneck = "*"
geopandas = "*"
geoviews = "*"
spatialpandas = "*"
fastparquet = "*"
xarray-simlab = "*"
hvplot = "*"
panel = ">=0.14"
cmasher = "*"
param = "*"
jupyterlab = ">=4"
ipympl = "*"
ipywidgets = "*"
jupyter_bokeh = ">=4.0.1"
pyviz_comms = "*"
selenium = "*"
geckodriver = "*"

# [pypi-dependencies]
# clearwater_data = { git = "https://github.com/EcohydrologyTeam/ClearWater-data.git" }
# clearwater_modules = { git = "https://github.com/EcohydrologyTeam/ClearWater-modules.git" }

# ===========================
# Dev feature (editable repos)
# ===========================
[feature.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pyright = "*"
snakeviz = "*"
python-lsp-server = "*"
pylsp-mypy = "*"
jupyterlab-lsp = "*"

[feature.dev.pypi-dependencies]
# "." refers to the current directory where src/ is located
clearwater_riverine = { path = ".", editable = true }
clearwater_data = { path = "../ClearWater-data", editable = true }
clearwater_modules = { path = "../ClearWater-modules", editable = true }

# ===========================
# Environments
# ===========================
[environments]
# Tell the 'dev' environment to ignore the git versions 
# and use our local paths instead.
dev = ["dev"]