[project]
name = "clearwater_riverine"
description = "Clearwater Python transport model"
authors = [
    {name = "Sarah Jordan", email = "sjordan@limno.com"},
    {name = "Jason M Rutyna", email = "jrutyna@limno.com"},
    {name = "Anthony Aufdenkampe", email = "aaufdenkampe@limno.com"},
    {name = "Paul Tomasula", email = "ptomasula@gmail.com"},
    {name = "Todd Steissberg", email = "Todd.E.Steissberg@erdc.dren.mil"},
]
dynamic = ["version", "readme"]
requires-python = ">= 3.11"
dependencies=[
    "cf-xarray",
    "dask",
    "geopandas",
    "h5py",
    "hdf5plugin", # compression filters
    "holoviews",
    "matplotlib",
    # "numba", # only used in archived files in sandbox
    "numpy",
    "pandas",
    "pyyaml",
    "scipy",
    "shapely",
    "xarray",
    "zarr", # dependency of clearwater-data, so not strictly required here
]


###############
### Build 
###############
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "./src/clearwater_riverine/__init__.py"

[tool.hatch.readme]
path = "./README.md"

[tool.hatch.metadata]
allow-direct-references = true


########################
### Pixi 
########################

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[tool.pixi.dependencies]
# Notebooks & Visualization
geoviews = "*"
hvplot = "*"
panel  = "*"
jupyterlab = "*"
jupyterlab-lsp = "*"
ipympl = "*"
ipywidgets = "*"
jupyter_bokeh = "*"
pyviz_comms = "*"
selenium = "*"
geckodriver = "*"
python-lsp-server = "*"
pylsp-mypy = "*"

[tool.pixi.pypi-dependencies]
clearwater_riverine = { path = ".", editable = true }
clearwater_data = { path = "../ClearWater-data", editable = true }


#############################
### Pixi Dev Environment
#############################

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.feature.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pyright = "*"
snakeviz = "*"

[tool.pixi.feature.dev.pypi-dependencies]
clearwater_riverine = { path = ".", editable = true }
clearwater_data = { path = "../ClearWater-data", editable = true }

[tool.pixi.tasks]
verify-install = {cmd = "python -c \"import clearwater_data; import clearwater_riverine; \""}

